---
# tasks file for sample
- name: copy a file 
  copy:
    src: abc.txt 
    dest: /home/ubuntu/abc_file.txt
- name: copying a template 
  template: 
    src: templates/abc.j2 
    dest: /home/ubuntu/abc_template.txt

- name: display abc template
  command: cat /home/ubuntu/abc_template.txt
  register: output
  notify: display
